spring.application.name=SteamTracker

scheduler.timezone=America/Sao_Paulo

scheduler.owned-games.cron=0 0 0 * * *
scheduler.recent-games.cron=0 0 18-23,0-3 * * *
scheduler.wishlist.cron=0 0 */2 * * *