spring.application.name=SteamTracker

scheduler.timezone=America/Sao_Paulo

scheduler.owned-games.cron=0 0 0 * * *
scheduler.recent-games.cron=0 0 18-23 * * *
scheduler.wishlist.cron=0 0 */2 * * *
scheduler.gaming-stats.cron=0 0 0 * * *
scheduler.near-completion.cron= 0 0 0 * * *
scheduler.backlog-assistant.cron=0 0 0 * * *
scheduler.resume-assistant.cron=0 0 0 * * *
scheduler.gaming-advisor.cron=0 0 0 * * 7

#scheduler.owned-games.cron=0 * * * * *
#scheduler.recent-games.cron=0 * * * * *
#scheduler.wishlist.cron=0 * * * * *
#scheduler.gaming-stats.cron=0 * * * * *
#scheduler.near-completion.cron=0 * * * * *
#scheduler.backlog-assistant.cron=0 * * * * *
#scheduler.resume-assistant.cron=0 * * * * *
#scheduler.gaming-advisor.cron=0 * * * * *